### ISSUE TITLE
Constructions need to accommodate more types of insulation values

### ISSUE THREAD

**Issue by nealkruis** [open229/ruleset-model-description-schema#176]
Some rulesets characterize constructions with multiple R-values, for example:

- Cavity vs. Continuous R-values
- Slab edge vs. perimeter R-values

**Comment by nealkruis** [comment]
I think this is the right approach. There are a lot of possible combinations of foundation related insulation:

- Horizontal vs. Vertical
- Interior vs. Exterior
- Slab gap vs. slab edge
- Whole slab
- Different depths
- Partial wall insulation

**Comment by JasonGlazer** [comment]
Based on my somewhat limited knowledge in this area, I came up with the following enumeration. Please let me know what is still missing.

```
InsulationLocationOptions:
  Object Type: "Enumeration"
  Enumerators:
    ABOVE_GROUND_WALL_EXTERIOR_CONTINUOUS:
      Description: "Continous insulation on exterior of an above ground wall"
    ABOVE_GROUND_WALL_INTERIOR_CONTINUOUS:
      Description: "Continous insulation on interior of an above ground wall"
    ABOVE_GROUND_WALL_FULL_CAVITY:
      Description: "Insulation within the cavity of an above ground wall that fills the entire cavity"
    ABOVE_GROUND_WALL_PARTIAL_CAVITY:
      Description: "Insulation within the cavity of an above ground wall that fills only part of the cavity"
    SLAB_HORIZONTAL_PERIMETER:
      Description: "Insulation on underside of the slab covering the perimeter"
    SLAB_HORIZONTAL_FULL:
      Description: "Insulation fully covering the underside of the slab"
    SLAB_VERTICAL:
      Description: "Insulation applied vertically next to edge of slab"
    NONE:
      Description: "None"
    OTHER:
      Description: "Other"


```
